# Generated by Django 4.2 on 2023-04-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARINGO_FOOTBALL_CLUB_SYSTEM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnumber', models.IntegerField()),
                ('fullname', models.CharField(max_length=30)),
                ('gender', models.EmailField(max_length=30)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('contact', models.IntegerField()),
                ('county', models.CharField(max_length=30)),
                ('school', models.CharField(max_length=30)),
                ('team', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
